# Workflow will do a fresh install and build of node using Yarn

name: Yarn CI

on:
  push:
    branches: [ development, staging, master ]
  pull_request:
    branches: [ development, staging, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      selected_node_version: 16

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.selected_node_version }}
        cache: yarn

    - name: Yarn install
      run: |
        yarn install

    - name: Yarn build
      run: |
        yarn build-dev
