# Workflow will do a fresh install and build of node using Yarn

name: Yarn CI

on:
  push:
    branches: [ development, staging, master ]
  pull_request:
    branches: [ development, staging, master ]

jobs:
  build:
    name: Yarn build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build-dev
